# Generated by Django 3.1.3 on 2020-11-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SData',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=3)),
                ('c1', models.CharField(max_length=20)),
                ('c2', models.CharField(max_length=20)),
                ('c3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=7)),
                ('sdata', models.ForeignKey(default='<django.db.models.fields.CharField>#<django.db.models.fields.CharField>', on_delete=django.db.models.deletion.CASCADE, to='shopping.sdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
