# Generated by Django 3.1.3 on 2020-11-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20201111_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='sdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.sdata'),
        ),
    ]
