# Generated by Django 3.1.3 on 2020-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20201111_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='c1',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c2',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c3',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
