# Generated by Django 3.1.3 on 2020-11-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20201111_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='c1',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c2',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c3',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
