# Generated by Django 3.1.3 on 2020-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20201111_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdata',
            name='idd',
            field=models.CharField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
