# Generated by Django 3.1.3 on 2020-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20201111_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='sdata',
        ),
        migrations.AddField(
            model_name='slot',
            name='idd',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
