# Generated by Django 3.1.3 on 2020-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20201111_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='c1',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c2',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='c3',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
