# Generated by Django 3.1.3 on 2020-11-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20201111_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('trans_no', models.TextField(max_length=1000)),
                ('total', models.IntegerField(default=0)),
                ('products', models.TextField(max_length=10000)),
                ('sdata', models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='shopping.sdata')),
            ],
        ),
    ]
