# Generated by Django 3.1.3 on 2020-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email_id',
            new_name='email',
        ),
    ]
