# Generated by Django 3.1.3 on 2020-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20201111_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('Grocerries', 'Grocerries')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.AddField(
            model_name='customer',
            name='p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='p9',
            field=models.IntegerField(default=0),
        ),
    ]
