# Generated by Django 3.1.3 on 2020-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_product_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
