# Generated by Django 3.1.3 on 2020-11-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_auto_20201112_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_id',
            new_name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
