# Generated by Django 3.1.3 on 2020-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_auto_20201112_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uid',
            field=models.CharField(max_length=21),
        ),
    ]
