# Generated by Django 3.1.3 on 2020-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_auto_20201112_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
