# Generated by Django 3.1.3 on 2020-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_customer_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p8',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p9',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='trans_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='Dairies',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='grocerries',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='medicines',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
