# Generated by Django 3.1.3 on 2020-11-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_auto_20201112_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Dairies',
            new_name='dairy',
        ),
    ]
