# Generated by Django 3.1.3 on 2020-11-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_auto_20201112_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dairy',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='grocerries',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='medicines',
        ),
    ]
