# Generated by Django 3.1.3 on 2020-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20201112_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dairy',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='grocerries',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='medicines',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
