# Generated by Django 3.1.2 on 2020-11-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_auto_20201121_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=21)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('stationary', models.TextField(blank=True, max_length=10000, null=True)),
                ('musical', models.TextField(blank=True, max_length=10000, null=True)),
                ('book', models.TextField(blank=True, max_length=10000, null=True)),
                ('check', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='shopping.slot')),
            ],
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Lender',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
